apiVersion: v1
kind: Service
metadata:
  name: planner
  namespace: predictive-autoscaling
  labels:
    app: planner
    component: autoscaling
spec:
  selector:
    app: planner
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
